
# HTTP Server
server:
  port: ${vcap.application.port:0}   # HTTP (Tomcat) port random


    
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:2222/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5 