
# HTTP Server
server:
  port: 0   # HTTP (Tomcat) port random


    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5 