server:
    port: 2222
    
eureka:
  instance:
    prefer-ip-address: true
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0     
    

#spring.boot.admin.url: http://localhost:3333               