server:
  port: 8080
    

zuul:
  routes:
    car-service:
      path: /car-serv/**
      serviceId: car-service
    get:
      path: /car-serv2/**
      #url: http://localhost:8082/cliente-car/
      serviceId: car-service
      
      
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}   
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:2222/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5