#  freemarker:
#    enabled: false           # Ignore Eureka dashboard FreeMarker templates
#  thymeleaf:
#    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
#    prefix: classpath:/templates/    # Trailing / mandatory  # Template location for this application only

 
# Discovery Server Access
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}   
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:1111/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
 
# HTTP Server
server:
  port: ${vcap.application.port:0}   # HTTP (Tomcat) port random
  
  
spring.boot.admin.url: http://localhost:8082
