#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config
#        git:
#          uri: https://github.com/rafabc/microservice-full-environment/tree/master/microservice_config_server/src/main/resources/config
#  profiles:
#     active: git
#security:
#  user: 
#    password: rafabc
#    name: user  



spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rafabc/microservice-full-environment/master/microservice_config_server/src/main/resources/config